### crear un carrito
POST http://localhost:4000/api/carrito
Content-Type: application/json

### eliminar un carrito

DELETE http://localhost:4000/api/carrito/1

### agregar un producto al carrito
POST http://localhost:4000/api/carrito/2/productos
Content-Type: application/json

{
    "id": "1"
}

### eliminar un producto del carrito
DELETE http://localhost:4000/api/carrito/2/productos/1